// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjauyi4P4zQTx9FVidAKMhJ-PwZXttu60',
    appId: '1:1037160274125:web:36d5c9762ce8e66b9ef184',
    messagingSenderId: '1037160274125',
    projectId: 'dana-92d55',
    authDomain: 'dana-92d55.firebaseapp.com',
    storageBucket: 'dana-92d55.appspot.com',
    measurementId: 'G-V78WEFNX2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFeTkacOlnRWeCYHxsbEkvzAPqzxGjWg',
    appId: '1:1037160274125:android:d624154862ed840c9ef184',
    messagingSenderId: '1037160274125',
    projectId: 'dana-92d55',
    storageBucket: 'dana-92d55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF3Y24xBYcAQLbORbnw2lZDjPRceqA3NY',
    appId: '1:1037160274125:ios:fbf9e61aa96e1add9ef184',
    messagingSenderId: '1037160274125',
    projectId: 'dana-92d55',
    storageBucket: 'dana-92d55.appspot.com',
    iosClientId: '1037160274125-eqshn12ep0epji1m8mp0g1aot5987gaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF3Y24xBYcAQLbORbnw2lZDjPRceqA3NY',
    appId: '1:1037160274125:ios:fbf9e61aa96e1add9ef184',
    messagingSenderId: '1037160274125',
    projectId: 'dana-92d55',
    storageBucket: 'dana-92d55.appspot.com',
    iosClientId: '1037160274125-eqshn12ep0epji1m8mp0g1aot5987gaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dana',
  );
}
